Repository four-uncles/saramara-community-server, pull requests merged in 2023-08, with the labels that each got.

#65 [Feat/게시글등록∙수정∙삭제] 이미지 업로드 API 분리 및 수정/삭제 API 개발
  src/main/java/com/kakao/saramaracommunity/attach/controller/AttachController.java
  src/main/java/com/kakao/saramaracommunity/attach/dto/request/AttachRequest.java
  src/main/java/com/kakao/saramaracommunity/attach/dto/response/AttachResponse.java
  src/main/java/com/kakao/saramaracommunity/attach/entity/Attach.java
  src/main/java/com/kakao/saramaracommunity/attach/service/AttachService.java
  src/main/java/com/kakao/saramaracommunity/attach/service/AttachServiceImpl.java
  src/test/java/com/kakao/saramaracommunity/attach/service/AttachServiceImplTest.java
Labels: ✨ Feature, ♻ Refactor, 🔨 Fix, ✅ Test

#64 Be/feat/member #48 member unregister(with batch)
  build.gradle
  src/main/java/com/kakao/saramaracommunity/SaramaraCommunityApplication.java
  src/main/java/com/kakao/saramaracommunity/common/entity/BaseTimeEntity.java
  src/main/java/com/kakao/saramaracommunity/member/batch/SoftDeletedMemberConfig.java
  src/main/java/com/kakao/saramaracommunity/member/controller/MemberController.java
  src/main/java/com/kakao/saramaracommunity/member/dto/MemberImageDto.java
  src/main/java/com/kakao/saramaracommunity/member/dto/MemberInfoResDto.java
  src/main/java/com/kakao/saramaracommunity/member/dto/SignUpDto.java
  src/main/java/com/kakao/saramaracommunity/member/entity/Member.java
  src/main/java/com/kakao/saramaracommunity/member/entity/MemberImage.java
  src/main/java/com/kakao/saramaracommunity/member/exception/ValidExceptionHandlingMethod.java
  src/main/java/com/kakao/saramaracommunity/member/repository/MemberRepository.java
  src/main/java/com/kakao/saramaracommunity/member/service/MemberServiceImpl.java
  src/main/java/com/kakao/saramaracommunity/member/service/MemberServiceMethod.java
  src/main/java/com/kakao/saramaracommunity/member/service/UserService.java
  src/main/java/com/kakao/saramaracommunity/security/oauth/CustomOAuth2UserService.java
  src/main/resources/schemaChange.sql
  src/test/java/com/kakao/saramaracommunity/member/batch/SoftDeletedMemberConfigTest.java
  src/test/java/com/kakao/saramaracommunity/member/repository/MemberRepositoryTest.java
Labels: 🐛 Bug, ✨ Feature

#66 [Feat/Refector] 예외 처리 기능 추가 및 Attach 도메인 비즈니스 로직 개선
  src/main/java/com/kakao/saramaracommunity/attach/controller/AttachController.java
  src/main/java/com/kakao/saramaracommunity/attach/controller/AttachControllerAdvice.java
  src/main/java/com/kakao/saramaracommunity/attach/dto/request/AttachRequest.java
  src/main/java/com/kakao/saramaracommunity/attach/dto/response/AttachResponse.java
  src/main/java/com/kakao/saramaracommunity/attach/exception/AttachErrorCode.java
  src/main/java/com/kakao/saramaracommunity/attach/exception/AttachNotFoundException.java
  src/main/java/com/kakao/saramaracommunity/attach/exception/ImageUploadOutOfRangeException.java
  src/main/java/com/kakao/saramaracommunity/attach/service/AttachService.java
  src/main/java/com/kakao/saramaracommunity/attach/service/AttachServiceImpl.java
  src/main/java/com/kakao/saramaracommunity/comment/controller/CommentControllerAdvice.java
  src/main/java/com/kakao/saramaracommunity/comment/exception/CommentErrorCode.java
  src/main/java/com/kakao/saramaracommunity/common/dto/Payload.java
  src/main/java/com/kakao/saramaracommunity/common/exception/CommonErrorCode.java
  src/main/java/com/kakao/saramaracommunity/common/exception/ErrorCode.java
  src/main/java/com/kakao/saramaracommunity/common/exception/GlobalExceptionHandler.java
  src/main/java/com/kakao/saramaracommunity/member/dto/MemberErrorCode.java
  src/main/java/com/kakao/saramaracommunity/member/dto/MemberResDto.java
  src/main/java/com/kakao/saramaracommunity/member/exception/MemberControllerAdvice.java
  src/main/java/com/kakao/saramaracommunity/member/exception/ValidExceptionHandlingMethod.java
  src/main/java/com/kakao/saramaracommunity/member/service/MemberServiceImpl.java
  src/main/java/com/kakao/saramaracommunity/member/service/MemberServiceMethod.java
  src/main/java/com/kakao/saramaracommunity/member/service/SignUpCheckingServiceImpl.java
  src/main/java/com/kakao/saramaracommunity/util/AwsS3Uploader.java
  src/test/java/com/kakao/saramaracommunity/attach/service/AttachServiceImplTest.java
Labels: ✨ Feature, ♻ Refactor, 🔨 Fix, ✅ Test

#74 [Hotfix] GlobalExceptionHandler의 유효성 검사시 발생할 에외 메서드 문제 해결
  src/main/java/com/kakao/saramaracommunity/common/dto/Payload.java
  src/main/java/com/kakao/saramaracommunity/common/exception/GlobalExceptionHandler.java
Labels: 🐛 Bug, 🔨 Fix

#72 [Feat] 게시글 예외 처리 로직 추가하기
  src/main/java/com/kakao/saramaracommunity/board/controller/BoardControllerAdvice.java
  src/main/java/com/kakao/saramaracommunity/board/dto/request/BoardRequestDto.java
  src/main/java/com/kakao/saramaracommunity/board/entity/Board.java
  src/main/java/com/kakao/saramaracommunity/board/exception/BoardErrorCode.java
  src/main/java/com/kakao/saramaracommunity/board/exception/BoardInternalServerException.java
  src/main/java/com/kakao/saramaracommunity/board/exception/BoardNotFoundException.java
  src/main/java/com/kakao/saramaracommunity/board/exception/BoardUnauthorizedException.java
  src/main/java/com/kakao/saramaracommunity/board/service/BoardServiceImpl.java
Labels: ✨ Feature, 🔨 Fix
