Repository four-uncles/saramara-community-server, pull requests merged in 2023-07, with the labels that each got.

#37 [Feat/게시글작성] 게시글 첨부 이미지 파일 등록하기
  .gitignore
  build.gradle
  src/main/java/com/kakao/saramaracommunity/attach/controller/AttachController.java
  src/main/java/com/kakao/saramaracommunity/attach/dto/request/AttachRequest.java
  src/main/java/com/kakao/saramaracommunity/attach/dto/response/AttachResponse.java
  src/main/java/com/kakao/saramaracommunity/attach/entity/Attach.java
  src/main/java/com/kakao/saramaracommunity/attach/entity/AttachType.java
  src/main/java/com/kakao/saramaracommunity/attach/repository/AttachRepository.java
  src/main/java/com/kakao/saramaracommunity/attach/service/AttachService.java
  src/main/java/com/kakao/saramaracommunity/attach/service/AttachServiceImpl.java
  src/main/java/com/kakao/saramaracommunity/config/AwsS3Config.java
  src/main/java/com/kakao/saramaracommunity/config/SecurityConfig.java
  src/main/java/com/kakao/saramaracommunity/util/AwsS3Uploader.java
  src/main/java/com/kakao/saramaracommunity/util/FileUtil.java
  src/main/resources/application.yml
  src/test/java/com/kakao/saramaracommunity/attach/AwsS3/AwsS3Test.java
  src/test/java/com/kakao/saramaracommunity/attach/service/AttachServiceImplTest.java
  src/test/java/com/kakao/saramaracommunity/config/AwsS3MockConfig.java
Labels: ✨ Feature, ⚙ Setting, ✅ Test, ➕ Dependency

#39 [Feat/게시글상세조회] 하나의 게시글 가져오기
  src/main/java/com/kakao/saramaracommunity/board/controller/BoardController.java
  src/main/java/com/kakao/saramaracommunity/board/dto/response/BoardResponseDto.java
  src/main/java/com/kakao/saramaracommunity/board/repository/BoardRepository.java
  src/main/java/com/kakao/saramaracommunity/board/service/BoardService.java
  src/main/java/com/kakao/saramaracommunity/board/service/BoardServiceImpl.java
Labels: ✨ Feature

#38 [Fix/회원가입, 예외처리] 불필요한 클래스 삭제 및 메서드 수정
  src/main/java/com/kakao/saramaracommunity/handler/MethodArgumentNotValidExceptionHandler.java
  src/main/java/com/kakao/saramaracommunity/handler/RestResponseExceptionHandler.java
  src/main/java/com/kakao/saramaracommunity/member/dto/ErrorCode.java
  src/main/java/com/kakao/saramaracommunity/member/exception/BadRequestException.java
  src/main/java/com/kakao/saramaracommunity/member/exception/CustomValidationExceprion.java
  src/main/java/com/kakao/saramaracommunity/member/exception/DuplicateMemberException.java
  src/main/java/com/kakao/saramaracommunity/member/exception/GlobalExceptionHandler.java
  src/main/java/com/kakao/saramaracommunity/member/exception/NotFoundMemberException.java
  src/main/java/com/kakao/saramaracommunity/member/exception/ValidExceptionHandlingMethod.java
  src/main/java/com/kakao/saramaracommunity/member/service/MemberServiceImpl.java
  src/main/java/com/kakao/saramaracommunity/member/service/MemberServiceMethod.java
Labels: 🐛 Bug, ♻ Refactor, 🔨 Fix

#45 [Feat/메인] 모든 게시글 가져오기
  src/main/java/com/kakao/saramaracommunity/board/controller/BoardController.java
  src/main/java/com/kakao/saramaracommunity/board/dto/response/BoardResponseDto.java
  src/main/java/com/kakao/saramaracommunity/board/entity/Board.java
  src/main/java/com/kakao/saramaracommunity/board/entity/CategoryBoard.java
  src/main/java/com/kakao/saramaracommunity/board/repository/BoardRepository.java
  src/main/java/com/kakao/saramaracommunity/board/service/BoardService.java
  src/main/java/com/kakao/saramaracommunity/board/service/BoardServiceImpl.java
Labels: ✨ Feature

#46 [Feat/회원관련] 회원정보 조회, 수정, 회원가입 기타
  src/main/java/com/kakao/saramaracommunity/config/SecurityConfig.java
  src/main/java/com/kakao/saramaracommunity/member/controller/MemberController.java
  src/main/java/com/kakao/saramaracommunity/member/dto/ChangePWDto.java
  src/main/java/com/kakao/saramaracommunity/member/dto/MemberInfoResDto.java
  src/main/java/com/kakao/saramaracommunity/member/dto/MemberResDto.java
  src/main/java/com/kakao/saramaracommunity/member/dto/SignUpDto.java
  src/main/java/com/kakao/saramaracommunity/member/entity/Member.java
  src/main/java/com/kakao/saramaracommunity/member/entity/Role.java
  src/main/java/com/kakao/saramaracommunity/member/exception/GlobalExceptionHandler.java
  src/main/java/com/kakao/saramaracommunity/member/exception/ValidExceptionHandlingMethod.java
  src/main/java/com/kakao/saramaracommunity/member/repository/MemberRepository.java
  src/main/java/com/kakao/saramaracommunity/member/service/MemberSerivce.java
  src/main/java/com/kakao/saramaracommunity/member/service/MemberServiceImpl.java
  src/main/java/com/kakao/saramaracommunity/member/service/MemberServiceMethod.java
  src/main/java/com/kakao/saramaracommunity/member/service/SignUpCheckingService.java
  src/main/java/com/kakao/saramaracommunity/member/service/SignUpCheckingServiceImpl.java
  src/test/java/com/kakao/saramaracommunity/member/repository/MemberRepositoryTest.java
  src/test/java/com/kakao/saramaracommunity/member/service/MemberServiceTest.java
Labels: ✨ Feature

#47 [Feat/게시글상세조회 및 메인] 게시글에 대한 이미지 목록 조회
  .gitignore
  src/main/java/com/kakao/saramaracommunity/attach/controller/AttachController.java
  src/main/java/com/kakao/saramaracommunity/attach/dto/request/AttachRequest.java
  src/main/java/com/kakao/saramaracommunity/attach/dto/response/AttachResponse.java
  src/main/java/com/kakao/saramaracommunity/attach/entity/Attach.java
  src/main/java/com/kakao/saramaracommunity/attach/repository/AttachRepository.java
  src/main/java/com/kakao/saramaracommunity/attach/service/AttachService.java
  src/main/java/com/kakao/saramaracommunity/attach/service/AttachServiceImpl.java
  src/test/java/com/kakao/saramaracommunity/attach/service/AttachServiceImplTest.java
Labels: ✨ Feature, ✅ Test

#44 [Feat/댓글전체조회, 댓글수정] 하나의 게시글에 대한 모든 댓글 가져오기 ,댓글 수정하기
  src/main/java/com/kakao/saramaracommunity/comment/controller/CommentController.java
  src/main/java/com/kakao/saramaracommunity/comment/dto/CommentListDTO.java
  src/main/java/com/kakao/saramaracommunity/comment/entity/Comment.java
  src/main/java/com/kakao/saramaracommunity/comment/repository/CommentRepository.java
  src/main/java/com/kakao/saramaracommunity/comment/service/CommentService.java
  src/main/java/com/kakao/saramaracommunity/comment/service/CommentServiceImpl.java
Labels: ✨ Feature

#54 [Feat/댓글 삭제] 댓글 삭제하기
  src/main/java/com/kakao/saramaracommunity/comment/controller/CommentController.java
  src/main/java/com/kakao/saramaracommunity/comment/service/CommentService.java
  src/main/java/com/kakao/saramaracommunity/comment/service/CommentServiceImpl.java
Labels: ✨ Feature

#55 [Feat/게시글수정] 게시글 수정하기
  src/main/java/com/kakao/saramaracommunity/board/controller/BoardController.java
  src/main/java/com/kakao/saramaracommunity/board/dto/request/BoardRequestDto.java
  src/main/java/com/kakao/saramaracommunity/board/entity/Board.java
  src/main/java/com/kakao/saramaracommunity/board/service/BoardService.java
  src/main/java/com/kakao/saramaracommunity/board/service/BoardServiceImpl.java
Labels: ✨ Feature

#59 [Feat/댓글 예외처리] 댓글 예외처리 작성하기
  src/main/java/com/kakao/saramaracommunity/comment/controller/CommentExceptionHandler.java
  src/main/java/com/kakao/saramaracommunity/comment/exception/CommentErrorCode.java
  src/main/java/com/kakao/saramaracommunity/comment/exception/CommentNotFoundException.java
  src/main/java/com/kakao/saramaracommunity/comment/service/CommentServiceImpl.java
  src/main/java/com/kakao/saramaracommunity/common/dto/Payload.java
  src/main/java/com/kakao/saramaracommunity/common/exception/CommonErrorCode.java
Labels: ✨ Feature
